title: Rowan Wilson
description: Rowan "Stag" Wilson is a community manager, social media manager & digital artist based in Central NY.

# disabled because we are using a custom domain
#baseurl: /business-frontpage

color-scheme: "#16463f" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
