# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Rowan Wilson
description: >- # this means to ignore newlines until "baseurl:"
  Rowan "Stag" Wilson is a gaming-oriented community & social media manager. He's also a digital artist and dog dad.
baseurl: "/" # the subpath of the site
url: "https://rowanjwilson.com" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: /home
      slug: /
    - name: /work
    - name: /blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: rowanjwilson@pm.me
      link: rowanjwilson@pm.me
    - name: Discord
      value: Stag#2355
      link: "https://discordapp.com/users/114651040057393154"
  follow:
#    - name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@stagrunner"
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/rowanjwilson
#    - name: GitHub
#      link: http://github.com/stagrunner
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
